#+TITLE: Installing GeneNetwork services

For the lastest version of this document check [[https://github.com/pjotrp/genenetwork2/tree/master/doc][here]].

* Table of Contents                                                     :TOC:
 - [[#introduction][Introduction]]
 - [[#install][Install]]
   - [[#tarball][Tarball]]
   - [[#docker][Docker]]
   - [[#with-source][With source]]
 - [[#running-gn2][Running GN2]]
 - [[#run-mysql-server][Run MySQL server]]
   - [[#install-mysql-with-gnu-guix][Install MySQL with GNU GUIx]]
   - [[#load-the-small-database-in-mysql][Load the small database in MySQL]]
 - [[#gn2-dependency-graph][GN2 Dependency Graph]]
 - [[#working-with-the-gn2-source-code][Working with the GN2 source code]]
 - [[#trouble-shooting][Trouble shooting]]
   - [[#importerror-no-module-named-jinja2][ImportError: No module named jinja2]]
   - [[#error-can-not-find-directory-homegn2_data][ERROR: can not find directory $HOME/gn2_data]]
   - [[#cant-run-a-module][Can't run a module]]
   - [[#rpy2-error-show-now-found][Rpy2 error 'show' now found]]
   - [[#mysql-cant-connect-server-through-socket-error][Mysql can't connect server through socket ERROR]]
 - [[#read-more][Read more]]

* Introduction

Large system deployments can get very [[http://biogems.info/contrib/genenetwork/gn2.svg ][complex]]. In this document we
explain the GeneNetwork version 2 (GN2) reproducible deployment system
which is based on GNU Guix (see also [[https://github.com/pjotrp/guix-notes/blob/master/README.md][Guix-notes]]). The Guix
system can be used to install GN with all its files and dependencies.

The official installation path is from a checked out version of the
main Guix package tree and that of the Genenetwork package tree. This
is how Genenetwork is running on the main web server(s). Current
supported versions can be found as the SHA values of [[https://gitlab.com/genenetwork/guix-bioinformatics][Guix
bioinformatics]] and [[https://gitlab.com/genenetwork/guix][GNU Guix]]. Ask the maintainers which branches to use
(typically gn-latest or gn-stable).

For a full view of runtime dependencies as defined by GNU Guix, see
an example of the [[#gn2-dependency-graph][GN2 Dependency Graph]].

* Install

The quickest way to install GN2 is by using a binary installation
(tarball or Docker image).  These installations are bundled by GNU
Guix and include all dependencies. You can install GeneNetwork on most
Linux distributions, including Debian, Ubuntu, Fedora and CentOS,
provided you have administrator privileges (root). The alternative is
a Docker installation.

** Tarball

Download the ~800Mb tarball from
[[http://files.genenetwork.org/software/binary_tarball/]]. Validate the checksum and
unpack to root, for example

: tar xvzf genenetwork2-2.10rc3-1538ffd-tarball-pack.tar.gz
: mv /gnu /
: mv /opt/genenetwork2 /opt/

Now you shoud be able to start the server with

: /opt/genenetwork2/bin/genenetwork2

When the server stops with a MySQL error [[#run-mysql-server][Run MySQL server]]
and set SQL_URI to point at it. For example:

: export SQL_URI=mysql://gn2:mysql_password@127.0.0.1/db_webqtl_s

See also [[#mysql-cant-connect-server-through-socket-error][Mysql can't connect server through socket ERROR]].

** Docker

Docker images are also available through
[[http://files.genenetwork.org/software/]]. Validate the checksum and run
with [[https://docs.docker.com/engine/reference/commandline/load/][Docker load]].

** With source

For more elaborate installation instructions on deploying GeneNetwork from
source see [[./development.org][development]].

* Running GN2

Default settings for GN2 are listed in a file called
[[../etc/default_settings.py][default_settings.py]]. You can copy this file and pass it as a new
parameter to the genenetwork2 command, e.g.

: genenetwork2 mysettings.py

or you can set environment variables to override individual parameters, e.g.

: env SERVER_PORT=5004 SQL_URI=mysql://user:pwd@dbhostname/db_webqtl genenetwork2

the debug and logging switches can be particularly useful when
developing GN2.

* Run MySQL server
** Install MySQL with GNU GUIx

These are the steps you can take to install a fresh installation of
mysql (which comes as part of the GNU Guix genenetwork2 install).

As root configure and run

:  adduser mysql && addgroup mysql
:  mysqld --datadir=/var/mysql --initialize-insecure
:  mkdir -p /var/run/mysqld
:  chown mysql.mysql ~/mysql /var/run/mysqld
:  mysqld -u mysql --datadir=/var/mysql --explicit_defaults_for_timestamp -P 12048

where 12048 is port to connect on.

If you want to run as root you may have to set

: /etc/my.cnf
: [mysqld]
: user=root

To check error output in a file on start-up run with something like

: mysqld -u mysql --console  --explicit_defaults_for_timestamp  --datadir=/gnu/mysql --log-error=~/test.log

GNU Guix installs mysqld in your profile, so this may work

: /home/user/.guix-profile/bin/mysqld -u mysql --explicit_defaults_for_timestamp  --datadir=/gnu/mysql

When you get errors like:

: sqlalchemy.exc.IntegrityError: (_mysql_exceptions.IntegrityError) (1215, 'Cannot add foreign key constraint')

you may need to set

: set foreign_key_checks=0

** Load the small database in MySQL

At this point we require the underlying distribution to install and
run mysqld (see next section for GNU Guix). Currently we have two databases for deployment,
'db_webqtl_s' is the small testing database containing experiments
from BXD mice and 'db_webqtl_plant' which contains all plant related
material.

Download one database from

[[http://files.genenetwork.org/raw_database/]]

[[https://s3.amazonaws.com/genenetwork2/db_webqtl_s.zip]]

Check the md5sum.

After installation inflate the database binary in the MySQL directory

: cd ~/mysql
: chown -R mysql:mysql db_webqtl_s/
: chmod 700 db_webqtl_s/
: chmod 660 db_webqtl_s/*

restart MySQL service (mysqld). Login as root

: myslq -u root

and

: mysql> show databases;
: +--------------------+
: | Database           |
: +--------------------+
: | information_schema |
: | db_webqtl_s        |
: | mysql              |
: | performance_schema |
: +--------------------+

Set permissions and match password in your settings file below:

: mysql> grant all privileges on db_webqtl_s.* to gn2@"localhost" identified by 'mysql_password';

You may need to change "localhost" to whatever domain you are
connecting from (mysql will give an error).

Note that if the mysql connection is not working, try connecting to
the IP address and check server firewall, hosts.allow and mysql IP
configuration (see below).

Note for the plant database you can rename it to db_webqtl_s, or
change the settings in etc/default_settings.py to match your path.

* GN2 Dependency Graph

Graph of all runtime dependencies as installed by GNU Guix.

#+ATTR_HTML: :title GN2_graph
http://biogems.info/contrib/genenetwork/gn2.svg

* Working with the GN2 source code

See [[development]].

* Trouble shooting

** ImportError: No module named jinja2

If you have all the Guix packages installed this error points out that
the environment variables are not set. Copy-paste the paths into your
terminal (mainly so PYTHON_PATH and R_LIBS_SITE are set) from the
information given by guix:

: guix package --search-paths

On one system:

: export PYTHONPATH="$HOME/.guix-profile/lib/python2.7/site-packages"
: export R_LIBS_SITE="$HOME/.guix-profile/site-library/"
: export GEM_PATH="$HOME/.guix-profile/lib/ruby/gems/2.2.0"

and perhaps a few more.
** ERROR: can not find directory $HOME/gn2_data

The default settings file looks in your $HOME/gn2_data. Since these
files come with a Guix installation you should take a hint from the
values in the installed version of default_settings.py (see above in
this document).

** Can't run a module

In rare cases, development modules are not brought in with Guix
because no source code is available. This can lead to missing modules
on a running server. Please check with the authors when a module
is missing.
** Rpy2 error 'show' now found

This error

: __show = rpy2.rinterface.baseenv.get("show")
: LookupError: 'show' not found

means that R was updated in your path, and that Rpy2 needs to be
recompiled against this R - don't you love informative messages?

In our case it means that GN's PYTHONPATH is not in sync with
R_LIBS_SITE. Please check your GNU Guix GN2 installation paths,
you man need to reinstall. Note that this may be the point you
may want to start using profiles (see profile section).

** Mysql can't connect server through socket ERROR

The following error

: sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (2002, 'Can\'t connect to local MySQL server through socket \'/run/mysqld/mysqld.sock\' (2 "No such file or directory")')

means that MySQL is trying to connect locally to a non-existent MySQL
server, something you may see in a container. Typically replicated with something like

: mysql -h localhost

try to connect over the network interface instead, e.g.

: mysql -h 127.0.0.1

if that works run genenetwork after setting SQL_URI to something like

: export SQL_URI=mysql://gn2:mysql_password@127.0.0.1/db_webqtl_s


* Read more

If you want to understand the architecture of GN2 read
[[Architecture.org]].  The rest of this document is mostly on deployment
of GN2. Also see the [[development.org][development]] section.
